name: Deploy react to gh-pages

permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install

      - name: Build
        run: |
          npm run deploy

      - name: Deploy build files to GitHub Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          gh-pages -d build
          git checkout main -- build
          git checkout gh-pages
          git add build -f
          git commit -m "Update gh-pages with build files"
          git push origin gh-pages
